vim.g.mapleader = " "

require("global")
require("options")
require("lsp")
require("colorscheme")
require("autocmds")
require("netrw")
require("statusline")
require("find")
require("grep")
require("diagnostics")
require("formating")
require("keymaps")
require("plugins")
